### ISSUE TITLE
Drive identifiers sometimes not an array

### ISSUE THREAD

**Issue by sosodev** [stmcginnis/gofish#147]
I noticed that `chassis.Drives()` was often returning a truncated slice of drives. A little bit of debugging revealed that `GetDrive` was failing to parse one of our drives that lists its `Identifiers` as an object instead of an array. Most of the drives do not do this but the returned drives slice was quite small because `chassis.Drives()` [returns early](https://github.com/stmcginnis/gofish/blob/main/redfish/chassis.go#L375) when it encounters an error for any drive in the list.

```yaml
  "Identifiers": {
    "DurableName": "5CD2E4D40DC20100",
    "DurableNameFormat": "EUI"
  },
```

Is this something you have encountered before? I don't know how to parse the variable type besides using an interface and type assertions but that seems hacky.
