### ISSUE TITLE
panic: json: cannot unmarshal string into Go struct field .temp.Voltages.temp.UpperThresholdNonCritical of type float32

### ISSUE THREAD

**Issue by webfrank** [stmcginnis/gofish#409]
Error trying to extract Power information from CISCO CIMC

**Comment by stmcginnis** [comment]
This is usually caused by the vendor implementation not following the spec and doing something like setting a numeric value to a string. Can you get the raw json response for the object so we can see what it's choking on?

**Comment by stmcginnis** [comment]
Just to capture it here, this is the definition for that property:

```yaml
        UpperThresholdNonCritical:
          description: The value at which the reading is above normal range.
          nullable: true
          readOnly: true
          type: number
          x-longDescription: This property shall contain the value at which the `ReadingVolts`
            property is above the normal range.  The value of the property shall use
            the same units as the `ReadingVolts` property.
          x-units: V
```

So if they are returning it as a string, this will have to be raised with Cisco to fix their implementation.
